name: Workflow Run Wait Temp
description: wait for all `workflow_run` required workflows to be successful; used for tests, don't rely on it

branding:
  color: blue
  icon: clock

inputs:
  github-token:
    description: The GitHub token used to post comments on pull requests
    default: ${{ github.token }}

  timeout:
    description: timeout before we stop trying (in milliseconds)
    default: 30000

  delay:
    description: delay between status checks (in milliseconds)
    default: 5000

runs:
  using: docker
  image: docker://ghcr.io/m0n5t3r/action-workflow-run-wait-temp
